<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>1388</X>
  <Y>268</Y>
  <VerticalWidth>522</VerticalWidth>
  <VerticalHeight>445</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFEBDBB2</TextColor>
    <BackgroundColor>FF282828</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>03FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>007B3333</SeparatorsColor>
    <PersonalBestColor>FF458588</PersonalBestColor>
    <AheadGainingTimeColor>FFB8BB26</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF98971A</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFFB4934</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC241D</BehindLosingTimeColor>
    <BestSegmentColor>FFD79921</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FFA89984</NotRunningColor>
    <PausedColor>FF928374</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>FF131313</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZVYnVudHUAAEBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZVYnVudHUAAC9CBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZVYnVudHUAAJBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TextFont>
    <AlwaysOnTop>False</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>True</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>SolidColor</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
    <MousePassThroughWhileRunning>False</MousePassThroughWhileRunning>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7.3</Version>
        <ShowGameName>True</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
        <ShowAttemptCount>True</ShowAttemptCount>
        <ShowFinishedRunsCount>True</ShowFinishedRunsCount>
        <OverrideTitleFont>True</OverrideTitleFont>
        <OverrideTitleColor>True</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZVYnVudHUAAGBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TitleFont>
        <SingleLine>True</SingleLine>
        <TitleColor>FFD79921</TitleColor>
        <BackgroundColor>00000000</BackgroundColor>
        <BackgroundColor2>FF131313</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DisplayGameIcon>True</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>True</ShowPlatform>
        <ShowVariables>True</ShowVariables>
        <TextAlignment>0</TextAlignment>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Subsplits.dll</Path>
      <Settings>
        <Version>1.7</Version>
        <AutomaticAbbreviation>False</AutomaticAbbreviation>
        <CurrentSplitTopColor>FF3C3836</CurrentSplitTopColor>
        <CurrentSplitBottomColor>00CA00CA</CurrentSplitBottomColor>
        <VisualSplitCount>6</VisualSplitCount>
        <SplitPreviewCount>0</SplitPreviewCount>
        <MinimumMajorSplits>0</MinimumMajorSplits>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>False</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <SplitTimesAccuracy>Hundredths</SplitTimesAccuracy>
        <BeforeNamesColor>FFEBDBB2</BeforeNamesColor>
        <CurrentNamesColor>FFEBDBB2</CurrentNamesColor>
        <AfterNamesColor>FFEBDBB2</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>27</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>6</SplitHeight>
        <CurrentSplitGradient>Plain</CurrentSplitGradient>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>01FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <HeaderComparison>Current Comparison</HeaderComparison>
        <HeaderTimingMethod>Current Timing Method</HeaderTimingMethod>
        <Display2Rows>False</Display2Rows>
        <IndentBlankIcons>True</IndentBlankIcons>
        <IndentSubsplits>True</IndentSubsplits>
        <HideSubsplits>False</HideSubsplits>
        <ShowSubsplits>False</ShowSubsplits>
        <CurrentSectionOnly>False</CurrentSectionOnly>
        <OverrideSubsplitColor>True</OverrideSubsplitColor>
        <SubsplitGradient>Plain</SubsplitGradient>
        <ShowHeader>True</ShowHeader>
        <IndentSectionSplit>True</IndentSectionSplit>
        <ShowIconSectionSplit>True</ShowIconSectionSplit>
        <ShowSectionIcon>True</ShowSectionIcon>
        <HeaderGradient>Plain</HeaderGradient>
        <OverrideHeaderColor>True</OverrideHeaderColor>
        <HeaderText>True</HeaderText>
        <HeaderTimes>True</HeaderTimes>
        <HeaderAccuracy>Tenths</HeaderAccuracy>
        <SectionTimer>True</SectionTimer>
        <SectionTimerGradient>False</SectionTimerGradient>
        <SectionTimerAccuracy>Tenths</SectionTimerAccuracy>
        <SubsplitTopColor>FF3C3836</SubsplitTopColor>
        <SubsplitBottomColor>00FC0101</SubsplitBottomColor>
        <HeaderTopColor>FF665C54</HeaderTopColor>
        <HeaderBottomColor>FFCA00CA</HeaderBottomColor>
        <HeaderTextColor>FF8EC07C</HeaderTextColor>
        <HeaderTimesColor>FFEBDBB2</HeaderTimesColor>
        <SectionTimerColor>FF83A598</SectionTimerColor>
        <ShowColumnLabels>True</ShowColumnLabels>
        <LabelsColor>FF8EC07C</LabelsColor>
        <Columns>
          <Settings>
            <Version>1.5</Version>
            <Name>+/-</Name>
            <Type>Delta</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
          <Settings>
            <Version>1.5</Version>
            <Name>seg</Name>
            <Type>SegmentDeltaorSegmentTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
          <Settings>
            <Version>1.5</Version>
            <Name>time</Name>
            <Type>SplitTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
        </Columns>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.DetailedTimer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <Height>85</Height>
        <Width>200</Width>
        <SegmentTimerSizeRatio>39</SegmentTimerSizeRatio>
        <TimerShowGradient>True</TimerShowGradient>
        <OverrideTimerColors>True</OverrideTimerColors>
        <SegmentTimerShowGradient>True</SegmentTimerShowGradient>
        <TimerFormat>1.23</TimerFormat>
        <SegmentTimerFormat>1.23</SegmentTimerFormat>
        <SegmentTimesAccuracy>Hundredths</SegmentTimesAccuracy>
        <TimerColor>FFB16286</TimerColor>
        <SegmentTimerColor>FFB16286</SegmentTimerColor>
        <SegmentLabelsColor>FF83A598</SegmentLabelsColor>
        <SegmentTimesColor>FF458588</SegmentTimesColor>
        <SegmentLabelsFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZVYnVudHUAADBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></SegmentLabelsFont>
        <SegmentTimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZVYnVudHUAADBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></SegmentTimesFont>
        <SplitNameFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAMEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SplitNameFont>
        <DisplayIcon>False</DisplayIcon>
        <IconSize>40</IconSize>
        <ShowSplitName>False</ShowSplitName>
        <SplitNameColor>FFFFFFFF</SplitNameColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <Comparison2>Current Comparison</Comparison2>
        <HideComparison>True</HideComparison>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>29</DecimalsSize>
        <SegmentTimerDecimalsSize>35</SegmentTimerDecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.PreviousSegment.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DeltaAccuracy>Tenths</DeltaAccuracy>
        <DropDecimals>True</DropDecimals>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
        <ShowPossibleTimeSave>False</ShowPossibleTimeSave>
        <TimeSaveAccuracy>Tenths</TimeSaveAccuracy>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.SumOfBest.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FF98971A</TextColor>
        <OverrideTextColor>True</OverrideTextColor>
        <TimeColor>FFB8BB26</TimeColor>
        <OverrideTimeColor>True</OverrideTimeColor>
        <Accuracy>Seconds</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Display2Rows>False</Display2Rows>
      </Settings>
    </Component>
  </Components>
</Layout>